[project]
name = "verbenform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Django==6.0.1",
    "django-environ>=0.12.0",
    "psycopg2-binary>=2.9.11",
    "requests>=2.32.5",
]
